- id: lint
  name: Lint (S)CSS
  entry: stylelint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - postcss@8.4.20
    - postcss-html@1.5.0
    - stylelint@14.16.1
    - stylelint-config-html@1.1.0
    - stylelint-config-standard-scss@6.1.0
    - stylelint-order@5.0.0
  types:
    - file
  files: \.(css|scss|sass|html|php)$
  exclude: (^node_modules|\.min\.css$)
