- id: lint
  name: Lint (S)CSS
  entry: stylelint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - postcss@8.5.3
    - postcss-html@1.8.0
    - stylelint@16.16.0
    - stylelint-config-html@1.1.0
    - stylelint-config-standard-scss@14.0.0
    - stylelint-order@6.0.4
  types:
    - file
  files: \.(css|scss|sass|html|php)$
  exclude: (^node_modules|\.min\.css$)
