- id: lint
  name: Lint (S)CSS
  entry: stylelint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - postcss@8.5.6
    - postcss-html@1.8.0
    - stylelint@16.25.0
    - stylelint-config-html@1.1.0
    - stylelint-config-standard-scss@16.0.0
    - stylelint-order@7.0.0
  types:
    - file
  files: \.(css|scss|sass|html|php)$
  exclude: (^node_modules|\.min\.css$)
