- id: lint
  name: Lint (S)CSS
  entry: stylelint
  language: node
  args:
    - '--fix'
  additional_dependencies:
    - postcss@8.4.21
    - postcss-html@1.5.0
    - stylelint@15.4.0
    - stylelint-config-html@1.1.0
    - stylelint-config-standard-scss@7.0.1
    - stylelint-order@6.0.3
  types:
    - file
  files: \.(css|scss|sass|html|php)$
  exclude: (^node_modules|\.min\.css$)
