name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: paulhfischer/update-node-hook-action@v1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
